# Generated by Django 3.0.8 on 2020-08-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0002_assignment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_on',
        ),
    ]
