# Generated by Django 3.0.8 on 2020-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0003_remove_assignment_assigned_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
